/******************************************************************************
*  Generated by PSoC Designer 5.1.1875.0
******************************************************************************/
#include <m8c.h>
// LED1 address and mask defines
#pragma	ioport	LED1_Data_ADDR:	0x0
BYTE			LED1_Data_ADDR;
#pragma	ioport	LED1_DriveMode_0_ADDR:	0x100
BYTE			LED1_DriveMode_0_ADDR;
#pragma	ioport	LED1_DriveMode_1_ADDR:	0x101
BYTE			LED1_DriveMode_1_ADDR;
#pragma	ioport	LED1_DriveMode_2_ADDR:	0x3
BYTE			LED1_DriveMode_2_ADDR;
#pragma	ioport	LED1_GlobalSelect_ADDR:	0x2
BYTE			LED1_GlobalSelect_ADDR;
#pragma	ioport	LED1_IntCtrl_0_ADDR:	0x102
BYTE			LED1_IntCtrl_0_ADDR;
#pragma	ioport	LED1_IntCtrl_1_ADDR:	0x103
BYTE			LED1_IntCtrl_1_ADDR;
#pragma	ioport	LED1_IntEn_ADDR:	0x1
BYTE			LED1_IntEn_ADDR;
#define LED1_MASK 0x1
// VR_IN address and mask defines
#pragma	ioport	VR_IN_Data_ADDR:	0x0
BYTE			VR_IN_Data_ADDR;
#pragma	ioport	VR_IN_DriveMode_0_ADDR:	0x100
BYTE			VR_IN_DriveMode_0_ADDR;
#pragma	ioport	VR_IN_DriveMode_1_ADDR:	0x101
BYTE			VR_IN_DriveMode_1_ADDR;
#pragma	ioport	VR_IN_DriveMode_2_ADDR:	0x3
BYTE			VR_IN_DriveMode_2_ADDR;
#pragma	ioport	VR_IN_GlobalSelect_ADDR:	0x2
BYTE			VR_IN_GlobalSelect_ADDR;
#pragma	ioport	VR_IN_IntCtrl_0_ADDR:	0x102
BYTE			VR_IN_IntCtrl_0_ADDR;
#pragma	ioport	VR_IN_IntCtrl_1_ADDR:	0x103
BYTE			VR_IN_IntCtrl_1_ADDR;
#pragma	ioport	VR_IN_IntEn_ADDR:	0x1
BYTE			VR_IN_IntEn_ADDR;
#define VR_IN_MASK 0x2
// LED3 address and mask defines
#pragma	ioport	LED3_Data_ADDR:	0x0
BYTE			LED3_Data_ADDR;
#pragma	ioport	LED3_DriveMode_0_ADDR:	0x100
BYTE			LED3_DriveMode_0_ADDR;
#pragma	ioport	LED3_DriveMode_1_ADDR:	0x101
BYTE			LED3_DriveMode_1_ADDR;
#pragma	ioport	LED3_DriveMode_2_ADDR:	0x3
BYTE			LED3_DriveMode_2_ADDR;
#pragma	ioport	LED3_GlobalSelect_ADDR:	0x2
BYTE			LED3_GlobalSelect_ADDR;
#pragma	ioport	LED3_IntCtrl_0_ADDR:	0x102
BYTE			LED3_IntCtrl_0_ADDR;
#pragma	ioport	LED3_IntCtrl_1_ADDR:	0x103
BYTE			LED3_IntCtrl_1_ADDR;
#pragma	ioport	LED3_IntEn_ADDR:	0x1
BYTE			LED3_IntEn_ADDR;
#define LED3_MASK 0x4
// LED4 address and mask defines
#pragma	ioport	LED4_Data_ADDR:	0x0
BYTE			LED4_Data_ADDR;
#pragma	ioport	LED4_DriveMode_0_ADDR:	0x100
BYTE			LED4_DriveMode_0_ADDR;
#pragma	ioport	LED4_DriveMode_1_ADDR:	0x101
BYTE			LED4_DriveMode_1_ADDR;
#pragma	ioport	LED4_DriveMode_2_ADDR:	0x3
BYTE			LED4_DriveMode_2_ADDR;
#pragma	ioport	LED4_GlobalSelect_ADDR:	0x2
BYTE			LED4_GlobalSelect_ADDR;
#pragma	ioport	LED4_IntCtrl_0_ADDR:	0x102
BYTE			LED4_IntCtrl_0_ADDR;
#pragma	ioport	LED4_IntCtrl_1_ADDR:	0x103
BYTE			LED4_IntCtrl_1_ADDR;
#pragma	ioport	LED4_IntEn_ADDR:	0x1
BYTE			LED4_IntEn_ADDR;
#define LED4_MASK 0x8
// LED2 address and mask defines
#pragma	ioport	LED2_Data_ADDR:	0x0
BYTE			LED2_Data_ADDR;
#pragma	ioport	LED2_DriveMode_0_ADDR:	0x100
BYTE			LED2_DriveMode_0_ADDR;
#pragma	ioport	LED2_DriveMode_1_ADDR:	0x101
BYTE			LED2_DriveMode_1_ADDR;
#pragma	ioport	LED2_DriveMode_2_ADDR:	0x3
BYTE			LED2_DriveMode_2_ADDR;
#pragma	ioport	LED2_GlobalSelect_ADDR:	0x2
BYTE			LED2_GlobalSelect_ADDR;
#pragma	ioport	LED2_IntCtrl_0_ADDR:	0x102
BYTE			LED2_IntCtrl_0_ADDR;
#pragma	ioport	LED2_IntCtrl_1_ADDR:	0x103
BYTE			LED2_IntCtrl_1_ADDR;
#pragma	ioport	LED2_IntEn_ADDR:	0x1
BYTE			LED2_IntEn_ADDR;
#define LED2_MASK 0x10
