/******************************************************************************
*  Generated by PSoC Designer 5.1.1875.0
******************************************************************************/
#include <m8c.h>
// SwitchIn address and mask defines
#pragma	ioport	SwitchIn_Data_ADDR:	0x4
BYTE			SwitchIn_Data_ADDR;
#pragma	ioport	SwitchIn_DriveMode_0_ADDR:	0x104
BYTE			SwitchIn_DriveMode_0_ADDR;
#pragma	ioport	SwitchIn_DriveMode_1_ADDR:	0x105
BYTE			SwitchIn_DriveMode_1_ADDR;
#pragma	ioport	SwitchIn_DriveMode_2_ADDR:	0x7
BYTE			SwitchIn_DriveMode_2_ADDR;
#pragma	ioport	SwitchIn_GlobalSelect_ADDR:	0x6
BYTE			SwitchIn_GlobalSelect_ADDR;
#pragma	ioport	SwitchIn_IntCtrl_0_ADDR:	0x106
BYTE			SwitchIn_IntCtrl_0_ADDR;
#pragma	ioport	SwitchIn_IntCtrl_1_ADDR:	0x107
BYTE			SwitchIn_IntCtrl_1_ADDR;
#pragma	ioport	SwitchIn_IntEn_ADDR:	0x5
BYTE			SwitchIn_IntEn_ADDR;
#define SwitchIn_MASK 0x8
// PWMOut address and mask defines
#pragma	ioport	PWMOut_Data_ADDR:	0x4
BYTE			PWMOut_Data_ADDR;
#pragma	ioport	PWMOut_DriveMode_0_ADDR:	0x104
BYTE			PWMOut_DriveMode_0_ADDR;
#pragma	ioport	PWMOut_DriveMode_1_ADDR:	0x105
BYTE			PWMOut_DriveMode_1_ADDR;
#pragma	ioport	PWMOut_DriveMode_2_ADDR:	0x7
BYTE			PWMOut_DriveMode_2_ADDR;
#pragma	ioport	PWMOut_GlobalSelect_ADDR:	0x6
BYTE			PWMOut_GlobalSelect_ADDR;
#pragma	ioport	PWMOut_IntCtrl_0_ADDR:	0x106
BYTE			PWMOut_IntCtrl_0_ADDR;
#pragma	ioport	PWMOut_IntCtrl_1_ADDR:	0x107
BYTE			PWMOut_IntCtrl_1_ADDR;
#pragma	ioport	PWMOut_IntEn_ADDR:	0x5
BYTE			PWMOut_IntEn_ADDR;
#define PWMOut_MASK 0x10
