/******************************************************************************
*  Generated by PSoC Designer 5.1.1875.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "PWM8_1.h"
#include "PWM8_2.h"

#endif
