/******************************************************************************
*  Generated by PSoC Designer 5.1.1875.0
******************************************************************************/
#include <m8c.h>
// SwitchInput address and mask defines
#pragma	ioport	SwitchInput_Data_ADDR:	0x4
BYTE			SwitchInput_Data_ADDR;
#pragma	ioport	SwitchInput_DriveMode_0_ADDR:	0x104
BYTE			SwitchInput_DriveMode_0_ADDR;
#pragma	ioport	SwitchInput_DriveMode_1_ADDR:	0x105
BYTE			SwitchInput_DriveMode_1_ADDR;
#pragma	ioport	SwitchInput_DriveMode_2_ADDR:	0x7
BYTE			SwitchInput_DriveMode_2_ADDR;
#pragma	ioport	SwitchInput_GlobalSelect_ADDR:	0x6
BYTE			SwitchInput_GlobalSelect_ADDR;
#pragma	ioport	SwitchInput_IntCtrl_0_ADDR:	0x106
BYTE			SwitchInput_IntCtrl_0_ADDR;
#pragma	ioport	SwitchInput_IntCtrl_1_ADDR:	0x107
BYTE			SwitchInput_IntCtrl_1_ADDR;
#pragma	ioport	SwitchInput_IntEn_ADDR:	0x5
BYTE			SwitchInput_IntEn_ADDR;
#define SwitchInput_MASK 0x1
// LedOut1 address and mask defines
#pragma	ioport	LedOut1_Data_ADDR:	0x4
BYTE			LedOut1_Data_ADDR;
#pragma	ioport	LedOut1_DriveMode_0_ADDR:	0x104
BYTE			LedOut1_DriveMode_0_ADDR;
#pragma	ioport	LedOut1_DriveMode_1_ADDR:	0x105
BYTE			LedOut1_DriveMode_1_ADDR;
#pragma	ioport	LedOut1_DriveMode_2_ADDR:	0x7
BYTE			LedOut1_DriveMode_2_ADDR;
#pragma	ioport	LedOut1_GlobalSelect_ADDR:	0x6
BYTE			LedOut1_GlobalSelect_ADDR;
#pragma	ioport	LedOut1_IntCtrl_0_ADDR:	0x106
BYTE			LedOut1_IntCtrl_0_ADDR;
#pragma	ioport	LedOut1_IntCtrl_1_ADDR:	0x107
BYTE			LedOut1_IntCtrl_1_ADDR;
#pragma	ioport	LedOut1_IntEn_ADDR:	0x5
BYTE			LedOut1_IntEn_ADDR;
#define LedOut1_MASK 0x2
// LedOut2 address and mask defines
#pragma	ioport	LedOut2_Data_ADDR:	0x4
BYTE			LedOut2_Data_ADDR;
#pragma	ioport	LedOut2_DriveMode_0_ADDR:	0x104
BYTE			LedOut2_DriveMode_0_ADDR;
#pragma	ioport	LedOut2_DriveMode_1_ADDR:	0x105
BYTE			LedOut2_DriveMode_1_ADDR;
#pragma	ioport	LedOut2_DriveMode_2_ADDR:	0x7
BYTE			LedOut2_DriveMode_2_ADDR;
#pragma	ioport	LedOut2_GlobalSelect_ADDR:	0x6
BYTE			LedOut2_GlobalSelect_ADDR;
#pragma	ioport	LedOut2_IntCtrl_0_ADDR:	0x106
BYTE			LedOut2_IntCtrl_0_ADDR;
#pragma	ioport	LedOut2_IntCtrl_1_ADDR:	0x107
BYTE			LedOut2_IntCtrl_1_ADDR;
#pragma	ioport	LedOut2_IntEn_ADDR:	0x5
BYTE			LedOut2_IntEn_ADDR;
#define LedOut2_MASK 0x4
// LedOut3 address and mask defines
#pragma	ioport	LedOut3_Data_ADDR:	0x4
BYTE			LedOut3_Data_ADDR;
#pragma	ioport	LedOut3_DriveMode_0_ADDR:	0x104
BYTE			LedOut3_DriveMode_0_ADDR;
#pragma	ioport	LedOut3_DriveMode_1_ADDR:	0x105
BYTE			LedOut3_DriveMode_1_ADDR;
#pragma	ioport	LedOut3_DriveMode_2_ADDR:	0x7
BYTE			LedOut3_DriveMode_2_ADDR;
#pragma	ioport	LedOut3_GlobalSelect_ADDR:	0x6
BYTE			LedOut3_GlobalSelect_ADDR;
#pragma	ioport	LedOut3_IntCtrl_0_ADDR:	0x106
BYTE			LedOut3_IntCtrl_0_ADDR;
#pragma	ioport	LedOut3_IntCtrl_1_ADDR:	0x107
BYTE			LedOut3_IntCtrl_1_ADDR;
#pragma	ioport	LedOut3_IntEn_ADDR:	0x5
BYTE			LedOut3_IntEn_ADDR;
#define LedOut3_MASK 0x8
// LedOut4 address and mask defines
#pragma	ioport	LedOut4_Data_ADDR:	0x4
BYTE			LedOut4_Data_ADDR;
#pragma	ioport	LedOut4_DriveMode_0_ADDR:	0x104
BYTE			LedOut4_DriveMode_0_ADDR;
#pragma	ioport	LedOut4_DriveMode_1_ADDR:	0x105
BYTE			LedOut4_DriveMode_1_ADDR;
#pragma	ioport	LedOut4_DriveMode_2_ADDR:	0x7
BYTE			LedOut4_DriveMode_2_ADDR;
#pragma	ioport	LedOut4_GlobalSelect_ADDR:	0x6
BYTE			LedOut4_GlobalSelect_ADDR;
#pragma	ioport	LedOut4_IntCtrl_0_ADDR:	0x106
BYTE			LedOut4_IntCtrl_0_ADDR;
#pragma	ioport	LedOut4_IntCtrl_1_ADDR:	0x107
BYTE			LedOut4_IntCtrl_1_ADDR;
#pragma	ioport	LedOut4_IntEn_ADDR:	0x5
BYTE			LedOut4_IntEn_ADDR;
#define LedOut4_MASK 0x10
// Bit5 address and mask defines
#pragma	ioport	Bit5_Data_ADDR:	0x4
BYTE			Bit5_Data_ADDR;
#pragma	ioport	Bit5_DriveMode_0_ADDR:	0x104
BYTE			Bit5_DriveMode_0_ADDR;
#pragma	ioport	Bit5_DriveMode_1_ADDR:	0x105
BYTE			Bit5_DriveMode_1_ADDR;
#pragma	ioport	Bit5_DriveMode_2_ADDR:	0x7
BYTE			Bit5_DriveMode_2_ADDR;
#pragma	ioport	Bit5_GlobalSelect_ADDR:	0x6
BYTE			Bit5_GlobalSelect_ADDR;
#pragma	ioport	Bit5_IntCtrl_0_ADDR:	0x106
BYTE			Bit5_IntCtrl_0_ADDR;
#pragma	ioport	Bit5_IntCtrl_1_ADDR:	0x107
BYTE			Bit5_IntCtrl_1_ADDR;
#pragma	ioport	Bit5_IntEn_ADDR:	0x5
BYTE			Bit5_IntEn_ADDR;
#define Bit5_MASK 0x20
// Bit6 address and mask defines
#pragma	ioport	Bit6_Data_ADDR:	0x4
BYTE			Bit6_Data_ADDR;
#pragma	ioport	Bit6_DriveMode_0_ADDR:	0x104
BYTE			Bit6_DriveMode_0_ADDR;
#pragma	ioport	Bit6_DriveMode_1_ADDR:	0x105
BYTE			Bit6_DriveMode_1_ADDR;
#pragma	ioport	Bit6_DriveMode_2_ADDR:	0x7
BYTE			Bit6_DriveMode_2_ADDR;
#pragma	ioport	Bit6_GlobalSelect_ADDR:	0x6
BYTE			Bit6_GlobalSelect_ADDR;
#pragma	ioport	Bit6_IntCtrl_0_ADDR:	0x106
BYTE			Bit6_IntCtrl_0_ADDR;
#pragma	ioport	Bit6_IntCtrl_1_ADDR:	0x107
BYTE			Bit6_IntCtrl_1_ADDR;
#pragma	ioport	Bit6_IntEn_ADDR:	0x5
BYTE			Bit6_IntEn_ADDR;
#define Bit6_MASK 0x40
// Bit7 address and mask defines
#pragma	ioport	Bit7_Data_ADDR:	0x4
BYTE			Bit7_Data_ADDR;
#pragma	ioport	Bit7_DriveMode_0_ADDR:	0x104
BYTE			Bit7_DriveMode_0_ADDR;
#pragma	ioport	Bit7_DriveMode_1_ADDR:	0x105
BYTE			Bit7_DriveMode_1_ADDR;
#pragma	ioport	Bit7_DriveMode_2_ADDR:	0x7
BYTE			Bit7_DriveMode_2_ADDR;
#pragma	ioport	Bit7_GlobalSelect_ADDR:	0x6
BYTE			Bit7_GlobalSelect_ADDR;
#pragma	ioport	Bit7_IntCtrl_0_ADDR:	0x106
BYTE			Bit7_IntCtrl_0_ADDR;
#pragma	ioport	Bit7_IntCtrl_1_ADDR:	0x107
BYTE			Bit7_IntCtrl_1_ADDR;
#pragma	ioport	Bit7_IntEn_ADDR:	0x5
BYTE			Bit7_IntEn_ADDR;
#define Bit7_MASK 0x80
