/******************************************************************************
*  Generated by PSoC Designer 5.1.1875.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "BaudClock.h"
#include "LCD.h"
#include "TX8.h"

#endif
